# Generated by Django 5.2 on 2025-05-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_slug',
            new_name='item_slug',
        ),
    ]
