# Generated by Django 5.2 on 2025-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
